import type { EventCode } from './types';

export const EVENT_CODES = {
  SYSTEM_UNHANDLED_ERROR: 'SYSTEM.ERROR.UNHANDLED',

  AUTH_PRACTICIEN_UNAUTHORIZED: 'AUTH.PRATICIEN.UNAUTHORIZED',
  AUTH_PROVIDER_ERROR: 'AUTH.PROVIDER.ERROR',

  PORTAIL_SESSION_INVALID_PAYLOAD: 'PORTAIL_PATIENT.SESSION.INVALID_PAYLOAD',
  PORTAIL_LIEN_PERMANENT_BASCULE: 'PORTAIL_PATIENT.LIEN_PERMANENT.BASCULE',
  PORTAIL_LIEN_PERMANENT_BASCULE_ILLISIBLE: 'PORTAIL_PATIENT.LIEN_PERMANENT.BASCULE_ILLISIBLE',
  PORTAIL_SESSION_FORBIDDEN: 'PORTAIL_PATIENT.SESSION.FORBIDDEN',
  PORTAIL_SESSION_EXCEPTION: 'PORTAIL_PATIENT.SESSION.EXCEPTION',
  PORTAIL_ASSIGNATIONS_UNAUTHORIZED: 'PORTAIL_PATIENT.ASSIGNATIONS.UNAUTHORIZED',
  PORTAIL_ASSIGNATIONS_QUERY_FAILED: 'PORTAIL_PATIENT.ASSIGNATIONS.QUERY_FAILED',

  // Gate G4 — lien magique. Le rejeu est refusé ET tracé : c'est une exigence
  // du registre, pas du confort de diagnostic.
  PORTAIL_LIEN_CONSOMME: 'PORTAIL_PATIENT.LIEN_MAGIQUE.CONSOMME',
  PORTAIL_LIEN_REJEU_REFUSE: 'PORTAIL_PATIENT.LIEN_MAGIQUE.REJEU_REFUSE',
  PORTAIL_LIEN_DEMANDE: 'PORTAIL_PATIENT.LIEN_MAGIQUE.DEMANDE',

  // Gate G5 — entrée patient par Google (IDP2 LOT-03c). Un seul code de refus
  // pour tous les motifs : l'adresse inconnue, le portail révoqué et le jeton
  // périmé se journalisent pareil. Les distinguer dans le log serait sans
  // danger, mais deux codes appellent deux messages, et deux messages finissent
  // par ressortir côté patient — c'est-à-dire un oracle.
  PORTAIL_GOOGLE_CONNEXION: 'PORTAIL_PATIENT.GOOGLE.CONNEXION',
  PORTAIL_GOOGLE_REFUS: 'PORTAIL_PATIENT.GOOGLE.REFUS',
  PORTAIL_GOOGLE_EXCEPTION: 'PORTAIL_PATIENT.GOOGLE.EXCEPTION',
  // Distinct de l'exception d'authentification : une trace d'accès perdue est un
  // trou de conformité (le lot existe pour le combler), pas un incident de
  // connexion. Les confondre rendrait la perte de trace inalertable.
  PORTAIL_GOOGLE_TRACE_ECHEC: 'PORTAIL_PATIENT.GOOGLE.TRACE_ECHEC',

  // Fin de parcours d'un dossier (IDP2). L'effacement est journalisé SANS
  // identité : sa trace durable est la ligne `dossiers_effaces`, un log étant
  // purgeable — et un log qui nommerait le patient effacé serait une
  // contradiction dans les termes.
  DOSSIER_SUIVI_CLOTURE: 'SECURITY.CYCLE_DE_VIE.SUIVI_CLOTURE',
  DOSSIER_EFFACE: 'SECURITY.CYCLE_DE_VIE.EFFACE',
  DOSSIER_CYCLE_DE_VIE_EXCEPTION: 'SECURITY.CYCLE_DE_VIE.EXCEPTION',

  QUESTIONNAIRE_SUBMIT_INVALID_PAYLOAD: 'QUESTIONNAIRE.SUBMIT.VALIDATION_FAILED',
  QUESTIONNAIRE_SUBMIT_FORBIDDEN: 'QUESTIONNAIRE.SUBMIT.FORBIDDEN',
  QUESTIONNAIRE_SUBMIT_ALREADY_DONE: 'QUESTIONNAIRE.SUBMIT.ALREADY_DONE',
  QUESTIONNAIRE_SUBMIT_EXPIRED: 'QUESTIONNAIRE.SUBMIT.EXPIRED',
  QUESTIONNAIRE_SUBMIT_UNAVAILABLE: 'QUESTIONNAIRE.SUBMIT.UNAVAILABLE',
  QUESTIONNAIRE_SUBMIT_EXCEPTION: 'QUESTIONNAIRE.SUBMIT.EXCEPTION',
  QUESTIONNAIRE_ACK_EMAIL_FAILED: 'QUESTIONNAIRE.SUBMIT.ACK_EMAIL_FAILED',

  ASSIGNATION_PACK_INVALID_PAYLOAD: 'ASSIGNATION.PACK.VALIDATION_FAILED',
  ASSIGNATION_PACK_RESOLUTION_FAILED: 'ASSIGNATION.PACK.RESOLUTION_FAILED',
  ASSIGNATION_PACK_EMAIL_FAILED: 'ASSIGNATION.PACK.EMAIL_SEND_FAILED',
  ASSIGNATION_PACK_EXCEPTION: 'ASSIGNATION.PACK.EXCEPTION',

  METRICS_UNAUTHORIZED: 'PRATICIEN.METRICS.UNAUTHORIZED',
  METRICS_QUERY_FAILED: 'PRATICIEN.METRICS.QUERY_FAILED',

  // G-TRUST-04, exigence 5 — journal des accès praticien. Comme
  // PORTAIL_GOOGLE_TRACE_ECHEC : une trace d'accès perdue est un trou de
  // conformité alertable pour lui-même, pas un incident applicatif. Couvre
  // l'écriture ET la purge de `journal_acces_dossiers`.
  PRATICIEN_ACCES_DOSSIER_TRACE_ECHEC: 'PRATICIEN.ACCES_DOSSIER.TRACE_ECHEC',

  SYNTHESE_GET_EXCEPTION: 'SYNTHESE_IA.GET.QUERY_FAILED',
  SYNTHESE_POST_CONTEXT_UNAVAILABLE: 'SYNTHESE_IA.GENERATION.CONTEXT_UNAVAILABLE',
  SYNTHESE_POST_EXCEPTION: 'SYNTHESE_IA.GENERATION.FAILED',
  SYNTHESE_PATCH_EXCEPTION: 'SYNTHESE_IA.UPDATE.FAILED',

  BOOKLET_GET_EXCEPTION: 'BOOKLET.PREVIEW.FAILED',
  BOOKLET_SEND_EXCEPTION: 'BOOKLET.SEND.FAILED',

  DOCUMENT_COMPOSE_EXCEPTION: 'PRATICIEN.DOCUMENT_C3.COMPOSE_FAILED',
} as const satisfies Record<string, EventCode>;

export type KnownEventCode = (typeof EVENT_CODES)[keyof typeof EVENT_CODES];
