import type { EventCode } from './types';

export const EVENT_CODES = {
  SYSTEM_UNHANDLED_ERROR: 'SYSTEM.ERROR.UNHANDLED',

  AUTH_PRACTICIEN_UNAUTHORIZED: 'AUTH.PRATICIEN.UNAUTHORIZED',
  AUTH_PROVIDER_ERROR: 'AUTH.PROVIDER.ERROR',

  PORTAIL_SESSION_INVALID_PAYLOAD: 'PORTAIL_PATIENT.SESSION.INVALID_PAYLOAD',
  PORTAIL_SESSION_FORBIDDEN: 'PORTAIL_PATIENT.SESSION.FORBIDDEN',
  PORTAIL_SESSION_EXCEPTION: 'PORTAIL_PATIENT.SESSION.EXCEPTION',
  PORTAIL_ASSIGNATIONS_UNAUTHORIZED: 'PORTAIL_PATIENT.ASSIGNATIONS.UNAUTHORIZED',
  PORTAIL_ASSIGNATIONS_QUERY_FAILED: 'PORTAIL_PATIENT.ASSIGNATIONS.QUERY_FAILED',

  // Gate G4 — lien magique. Le rejeu est refusé ET tracé : c'est une exigence
  // du registre, pas du confort de diagnostic.
  PORTAIL_LIEN_CONSOMME: 'PORTAIL_PATIENT.LIEN_MAGIQUE.CONSOMME',
  PORTAIL_LIEN_REJEU_REFUSE: 'PORTAIL_PATIENT.LIEN_MAGIQUE.REJEU_REFUSE',
  PORTAIL_LIEN_DEMANDE: 'PORTAIL_PATIENT.LIEN_MAGIQUE.DEMANDE',

  QUESTIONNAIRE_SUBMIT_INVALID_PAYLOAD: 'QUESTIONNAIRE.SUBMIT.VALIDATION_FAILED',
  QUESTIONNAIRE_SUBMIT_FORBIDDEN: 'QUESTIONNAIRE.SUBMIT.FORBIDDEN',
  QUESTIONNAIRE_SUBMIT_ALREADY_DONE: 'QUESTIONNAIRE.SUBMIT.ALREADY_DONE',
  QUESTIONNAIRE_SUBMIT_EXPIRED: 'QUESTIONNAIRE.SUBMIT.EXPIRED',
  QUESTIONNAIRE_SUBMIT_EXCEPTION: 'QUESTIONNAIRE.SUBMIT.EXCEPTION',
  QUESTIONNAIRE_ACK_EMAIL_FAILED: 'QUESTIONNAIRE.SUBMIT.ACK_EMAIL_FAILED',

  ASSIGNATION_PACK_INVALID_PAYLOAD: 'ASSIGNATION.PACK.VALIDATION_FAILED',
  ASSIGNATION_PACK_RESOLUTION_FAILED: 'ASSIGNATION.PACK.RESOLUTION_FAILED',
  ASSIGNATION_PACK_EMAIL_FAILED: 'ASSIGNATION.PACK.EMAIL_SEND_FAILED',
  ASSIGNATION_PACK_EXCEPTION: 'ASSIGNATION.PACK.EXCEPTION',

  METRICS_UNAUTHORIZED: 'PRATICIEN.METRICS.UNAUTHORIZED',
  METRICS_QUERY_FAILED: 'PRATICIEN.METRICS.QUERY_FAILED',

  SYNTHESE_GET_EXCEPTION: 'SYNTHESE_IA.GET.QUERY_FAILED',
  SYNTHESE_POST_CONTEXT_UNAVAILABLE: 'SYNTHESE_IA.GENERATION.CONTEXT_UNAVAILABLE',
  SYNTHESE_POST_EXCEPTION: 'SYNTHESE_IA.GENERATION.FAILED',
  SYNTHESE_PATCH_EXCEPTION: 'SYNTHESE_IA.UPDATE.FAILED',

  BOOKLET_GET_EXCEPTION: 'BOOKLET.PREVIEW.FAILED',
  BOOKLET_SEND_EXCEPTION: 'BOOKLET.SEND.FAILED',

  DOCUMENT_COMPOSE_EXCEPTION: 'PRATICIEN.DOCUMENT_C3.COMPOSE_FAILED',
} as const satisfies Record<string, EventCode>;

export type KnownEventCode = (typeof EVENT_CODES)[keyof typeof EVENT_CODES];
