import { O_RPS, O_JPT, O_04, O_03jt, O_YN, O_UPPS, O_YOUNG, O_BMS, O_CUNGI, O_PAS, O_ZARIT, O_DASS, O_CONNERS, q, qn, qs } from './shared';

export const Q_PED_01 = {
  id:'Q_PED_01', titre:'Échelle de Matinalité-Vespéralité Enfant — Dr Caci',
  instructions:'Pour chaque question, choisissez une seule réponse, celle qui correspond le mieux au rythme spontané de l\'enfant.',
  sections:[
    { id:'A', titre:'Préférences de sommeil et d\'éveil',
      questions:[
        q('PE1','Imagine que l\'école n\'existe plus. Tu n\'es pas obligé(e) de te lever tôt. À quelle heure te lèverais-tu ?',[{v:5,l:'Entre 5h00 et 6h30'},{v:4,l:'Entre 6h30 et 7h45'},{v:3,l:'Entre 7h45 et 9h45'},{v:2,l:'Entre 9h45 et 11h00'},{v:1,l:'Entre 11h00 et midi'}]),
        q('PE2','Chaque jour pour toi, te lever le matin c\'est :',[{v:1,l:'Impossible'},{v:2,l:'Difficile'},{v:3,l:'Plutôt facile'},{v:4,l:'Très facile'}]),
        q('PE3','Si les cours de gymnastique avaient lieu à 7h00 du matin, comment te sentirais-tu ?',[{v:4,l:'Au top niveau'},{v:3,l:'Bien'},{v:2,l:'Moins bien que d\'habitude'},{v:1,l:'Très mal'}]),
        q('PE4','Mauvaise nouvelle : tu as un contrôle de deux heures ! Bonne nouvelle : tu peux choisir de le faire à l\'heure où tu penses être le plus efficace. Ce sera :',[{v:4,l:'Entre 8h00 et 10h00'},{v:3,l:'Entre 11h00 et 13h00'},{v:2,l:'Entre 15h00 et 17h00'},{v:1,l:'Entre 19h00 et 21h00'}]),
        q('PE5','À quel moment de la journée as-tu le plus d\'énergie pour faire ce qui te plaît ?',[{v:4,l:'Le matin, car le soir je suis fatigué'},{v:3,l:'Le matin plus que le soir'},{v:2,l:'Le soir plus que le matin'},{v:1,l:'Le soir, car le matin je suis fatigué'}]),
        q('PE6','Chouette ! Tes parents te laissent te coucher à l\'heure que tu veux. Quel moment choisis-tu ?',[{v:5,l:'Entre 20h00 et 21h00'},{v:4,l:'Entre 21h00 et 22h15'},{v:3,l:'Entre 22h15 et 0h30'},{v:2,l:'Entre 0h30 et 1h45'},{v:1,l:'Entre 1h45 et 3h00'}]),
        q('PE7','Comment te sens-tu dans la demi-heure qui suit ton réveil ?',[{v:1,l:'Complètement épuisé'},{v:2,l:'Un petit peu étourdi'},{v:3,l:'Bien'},{v:4,l:'Au top niveau'}]),
        q('PE8','À quel moment ton corps commence-t-il à te dire qu\'il faut aller se coucher, même si tu peux résister encore un peu ?',[{v:5,l:'Entre 20h00 et 21h00'},{v:4,l:'Entre 21h00 et 22h15'},{v:3,l:'Entre 22h15 et 0h30'},{v:2,l:'Entre 0h30 et 1h45'},{v:1,l:'Entre 1h45 et 3h00'}]),
        q('PE9','Imaginons que tu doives te lever tous les matins à 6h00. Ça serait ?',[{v:1,l:'Affreux'},{v:2,l:'Pas super'},{v:3,l:'S\'il le faut absolument...'},{v:4,l:'Sans problème'}]),
        q('PE10','Lorsque tu te lèves le matin, combien de temps te faut-il pour te sentir bien réveillé ?',[{v:4,l:'Entre 0 et 10 minutes'},{v:3,l:'Entre 11 et 20 minutes'},{v:2,l:'Entre 21 et 40 minutes'},{v:1,l:'Plus de 40 minutes'}]),
      ]},
  ],
  scoring:{
    type:'sum_no_interpretation', maxTotal:43
  }
};
export const Q_PED_02 = {
  id:'Q_PED_02', titre:'Échelle de Conners — Version Enseignant (TDAH, forme courte)',
  instructions:'Ce questionnaire est destiné aux ENSEIGNANTS. Évaluez le comportement de l\'élève au cours du dernier mois. 0 = Pas du tout · 1 = Un peu · 2 = Souvent · 3 = Très souvent.',
  sections:[
    { id:'A', titre:'Opposition et comportement',
      questions:[
        q('CE1','Est excitable, impulsif(ve)',           [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE2','A du mal à rester assis(e) — se lève souvent',   [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE3','Est facilement distrait(e) par des stimulations extérieures', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE4','Oublie ce qu\'il/elle a déjà appris',  [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE5','Interrompt ou s\'immisce dans les activités des autres', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE6','Répond sans réfléchir aux questions — avant la fin de la question', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE7','A du mal à attendre son tour',         [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
      ]},
    { id:'B', titre:'Inattention et cognitif',
      questions:[
        q('CE8','Ne fait pas attention aux détails / fait des erreurs d\'étourderie', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE9','A du mal à soutenir l\'attention sur une tâche ou un jeu', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE10','Ne semble pas écouter quand on lui parle directement', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE11','Ne suit pas les instructions / ne termine pas les tâches', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE12','A du mal à organiser son travail ou ses activités', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE13','Évite les tâches qui demandent un effort mental soutenu', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE14','Perd souvent les affaires nécessaires aux tâches',  [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
      ]},
    { id:'C', titre:'Hyperactivité',
      questions:[
        q('CE15','Bouge sans cesse les mains ou les pieds — se tortille', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE16','Quitte sa place en classe / dans d\'autres situations', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE17','Court ou grimpe de façon excessive dans des situations inappropriées', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE18','A du mal à jouer calmement',           [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE19','Parle trop',                            [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE20','Agit comme si il/elle était "sur la brèche"', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
      ]},
    { id:'D', titre:'Index TDAH — Items clés',
      questions:[
        q('CE21','Ses résultats scolaires sont en dessous de ses capacités', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE22','Manque d\'attention — se perd facilement dans sa rêverie', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE23','Est facilement frustré(e) dans ses efforts',  [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE24','Difficultés à démarrer ou terminer le travail de classe', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE25','Changements d\'humeur rapides et imprévisibles', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE26','Ne persévère pas sur les tâches si elles demandent un effort', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE27','Ses relations avec les pairs sont difficiles', [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
        q('CE28','Perturbateur(trice) en classe',               [{v:0,l:'0'},{v:1,l:'1'},{v:2,l:'2'},{v:3,l:'3'}]),
      ]},
  ],
  scoring:{
    type:'subscore',
    subScores:[
      {id:'OPP',label:'Opposition / Impulsivité',items:['CE1','CE2','CE5','CE6','CE7'],max:15},
      {id:'INA',label:'Inattention / Cognitif',  items:['CE3','CE4','CE8','CE9','CE10','CE11','CE12','CE13','CE14'],max:27},
      {id:'HYP',label:'Hyperactivité',            items:['CE15','CE16','CE17','CE18','CE19','CE20'],max:18},
      {id:'IDX',label:'Index TDAH',               items:['CE21','CE22','CE23','CE24','CE25','CE26','CE27','CE28'],max:24},
    ]
  }
};
export const Q_PED_03 = {
  id:'Q_PED_03', titre:"Échelle d'évaluation Conners 3 pour le parent",
  instructions:"Voici des choses que des parents peuvent dire de leurs enfants. Répondre en décrivant l'enfant et ce qui s'est passé au cours du dernier mois. Lire attentivement chaque item puis indiquer à quel point il décrit bien l'enfant. Encerclez seulement une réponse pour chaque item. Il est important de répondre à tous les items. Donner la meilleure réponse possible pour les items jugés difficiles.",
  sections:[
    { id:"A", titre:"Items 1 à 36",
      description:'0 = Pas vrai du tout · 1 = Un peu vrai · 2 = Assez vrai · 3 = Très vrai',
      questions:[
        q("CP001","Est heureux(se), joyeux(se) et a une attitude positive.",O_CONNERS),
        q("CP002","Oublie durant ses activités quotidiennes.",O_CONNERS),
        q("CP003","Parle trop.",O_CONNERS),
        q("CP004","S'inquiète de beaucoup de choses.",O_CONNERS),
        q("CP005","Son orthographe est de mauvaise qualité.",O_CONNERS),
        q("CP006","Il/elle sèche des cours, absent de l'école sans autorisation.",O_CONNERS),
        q("CP007","Ne comprend pas ce qu'il/elle lit.",O_CONNERS),
        q("CP008","Il est agréable d'être avec lui/elle.",O_CONNERS),
        q("CP009","Mémorise bien les faits.",O_CONNERS),
        q("CP010","N'est pas invité/e à jouer ou à sortir avec les autres.",O_CONNERS),
        q("CP011","A forcé quelqu'un à avoir des activités sexuelles.",O_CONNERS),
        q("CP012","A de la difficulté à demeurer concentré/e sur une chose à la fois.",O_CONNERS),
        q("CP013","N'a pas d'amis/es.",O_CONNERS),
        q("CP014","Se met en colère.",O_CONNERS),
        q("CP015","Oublie des choses déjà apprises.",O_CONNERS),
        q("CP016","Intimide, menace ou fait peur aux autres.",O_CONNERS),
        q("CP017","Se sent sans valeur.",O_CONNERS),
        q("CP018","Je ne peux pas comprendre ce qui le/la rend heureux/se.",O_CONNERS),
        q("CP019","A la bougeotte, gigote.",O_CONNERS),
        q("CP020","A de la difficulté à contrôler ses inquiétudes.",O_CONNERS),
        q("CP021","Blâme les autres pour ses erreurs ou ses mauvais comportements.",O_CONNERS),
        q("CP022","Est sans cœur et cruel/le.",O_CONNERS),
        q("CP023","A une brève capacité d'attention.",O_CONNERS),
        q("CP024","A de la difficulté à garder ses amis/es.",O_CONNERS),
        q("CP025","Pleure souvent et facilement.",O_CONNERS),
        q("CP026","Ne peut pas faire les choses correctement.",O_CONNERS),
        q("CP027","Se sert d'une arme, par exemple un bâton, une brique, une bouteille brisée, un couteau ou une arme à feu.",O_CONNERS),
        q("CP028","Évite ou n'aime pas les choses qui demandent beaucoup d'efforts et qui ne sont pas amusantes.",O_CONNERS),
        q("CP029","Son humeur change rapidement et de manière radicale.",O_CONNERS),
        q("CP030","Initie délibérément des batailles avec les autres.",O_CONNERS),
        q("CP031","Fait des erreurs.",O_CONNERS),
        q("CP032","Il est difficile de lui plaire ou de l'amuser.",O_CONNERS),
        q("CP033","Dit la vérité, ne dit même pas de petits mensonges.",O_CONNERS),
        q("CP034","Ne termine pas ce qu'il/elle commence.",O_CONNERS),
        q("CP035","Ne semble pas écouter ce qui lui est dit.",O_CONNERS),
        q("CP036","A de la difficulté en lecture.",O_CONNERS)
      ]},
    { id:"B", titre:"Items 37 à 72",
      description:'0 = Pas vrai du tout · 1 = Un peu vrai · 2 = Assez vrai · 3 = Très vrai',
      questions:[
        q("CP037","A de la difficulté à débuter des tâches ou des projets.",O_CONNERS),
        q("CP038","Doit travailler très fort pour compléter les tâches difficiles.",O_CONNERS),
        q("CP039","Blesse physiquement les gens.",O_CONNERS),
        q("CP040","Il faut répondre à ses demandes immédiatement : est facilement frustré.",O_CONNERS),
        q("CP041","Est cruel/le envers les animaux.",O_CONNERS),
        q("CP042","Il est difficile de le/la motiver, même avec des friandises ou de l'argent.",O_CONNERS),
        q("CP043","Donne la réponse avant la fin de la question.",O_CONNERS),
        q("CP044","A de la difficulté à se concentrer.",O_CONNERS),
        q("CP045","Bouge constamment.",O_CONNERS),
        q("CP046","Ment pour blesser les gens.",O_CONNERS),
        q("CP047","Ne porte pas attention aux détails, fait des fautes d'inattention.",O_CONNERS),
        q("CP048","Est en colère et éprouve du ressentiment.",O_CONNERS),
        q("CP049","A de la difficulté à passer d'une activité à une autre.",O_CONNERS),
        q("CP050","Excitable, impulsif/ve.",O_CONNERS),
        q("CP051","A besoin d'explications supplémentaires sur les consignes.",O_CONNERS),
        q("CP052","Devient surstimulé/e.",O_CONNERS),
        q("CP053","Apprend les informations de manière séparée ; ne saisit pas la vue d'ensemble.",O_CONNERS),
        q("CP054","Agit comme s'il/si elle était animé/e par un moteur.",O_CONNERS),
        q("CP055","Dit la première chose qui lui vient à l'esprit.",O_CONNERS),
        q("CP056","Ment afin d'éviter de faire certaines choses ou afin d'obtenir les choses qu'il/elle veut.",O_CONNERS),
        q("CP057","Essaie de se venger.",O_CONNERS),
        q("CP058","Vole en cachette, par exemple vol à l'étalage ou falsification.",O_CONNERS),
        q("CP059","Embête ou ennuie délibérément les autres.",O_CONNERS),
        q("CP060","Lit lentement et avec beaucoup d'efforts.",O_CONNERS),
        q("CP061","A de la difficulté à attendre son tour.",O_CONNERS),
        q("CP062","Est parmi les derniers à être choisi par une équipe ou pour un jeu.",O_CONNERS),
        q("CP063","Complète ses projets à la dernière minute.",O_CONNERS),
        q("CP064","Interagit bien avec les autres enfants.",O_CONNERS),
        q("CP065","Endommage ou détruit volontairement les choses des autres.",O_CONNERS),
        q("CP066","Semble fatigué/e, a peu d'énergie.",O_CONNERS),
        q("CP067","Inattentif/ve, facilement distrait/e.",O_CONNERS),
        q("CP068","Ne suit pas les consignes, même lorsqu'il/elle les comprend et essaie de coopérer.",O_CONNERS),
        q("CP069","Court ou grimpe quand il/elle ne devrait pas le faire.",O_CONNERS),
        q("CP070","Semble « sur les nerfs », nerveux/se, tendu/e.",O_CONNERS),
        q("CP071","Est bruyant/e lors des jeux et des temps libres.",O_CONNERS),
        q("CP072","Planifie bien les choses.",O_CONNERS)
      ]},
    { id:"C", titre:"Items 73 à 108",
      description:'0 = Pas vrai du tout · 1 = Un peu vrai · 2 = Assez vrai · 3 = Très vrai',
      questions:[
        q("CP073","Est irritable et facilement embêté/e par les autres.",O_CONNERS),
        q("CP074","Se comporte comme un ange.",O_CONNERS),
        q("CP075","Oublie de remettre ses travaux complétés.",O_CONNERS),
        q("CP076","S'enfuit de la maison pour au moins une nuit, fugue.",O_CONNERS),
        q("CP077","S'ennuie.",O_CONNERS),
        q("CP078","A délibérément mis le feu afin de causer des dommages.",O_CONNERS),
        q("CP079","Ne complète pas ses travaux scolaires ou ses tâches, même lorsqu'il/elle les comprend et qu'il/elle essaie de coopérer.",O_CONNERS),
        q("CP080","Est patient/e et satisfait/e même lorsqu'il/elle attend longtemps.",O_CONNERS),
        q("CP081","A des crises de colère.",O_CONNERS),
        q("CP082","N'a plus de plaisir ou d'intérêt pour les activités.",O_CONNERS),
        q("CP083","Menace de blesser les autres.",O_CONNERS),
        q("CP084","A de la difficulté à organiser des tâches ou des activités.",O_CONNERS),
        q("CP085","Dérange les autres enfants.",O_CONNERS),
        q("CP086","Jure ou utilise un langage inapproprié.",O_CONNERS),
        q("CP087","N'arrive pas à saisir l'arithmétique.",O_CONNERS),
        q("CP088","Abandonne facilement les tâches difficiles.",O_CONNERS),
        q("CP089","Est déjà entré/e par effraction dans la maison, l'édifice ou la voiture de quelqu'un.",O_CONNERS),
        q("CP090","Est désordonné/e et désorganisé/e.",O_CONNERS),
        q("CP091","Sort tard le soir, même si c'est contre les règles.",O_CONNERS),
        q("CP092","Ne sait pas comment se faire des amis/es.",O_CONNERS),
        q("CP093","Quitte son siège lorsqu'il/elle devrait rester assis/e.",O_CONNERS),
        q("CP094","Refuse activement de faire ce que les adultes lui demandent.",O_CONNERS),
        q("CP095","A de la difficulté à demeurer concentré/e sur un travail ou un jeu pour une longue période de temps.",O_CONNERS),
        q("CP096","Vole en confrontant quelqu'un, par exemple agression, vol de sac à main ou vol à main armée.",O_CONNERS),
        q("CP097","Perd des choses, par exemple des travaux scolaires, des crayons, des livres, des outils ou des jouets.",O_CONNERS),
        q("CP098","Gigote ou se tortille sur son siège.",O_CONNERS),
        q("CP099","Agité/e ou hyperactif/ve.",O_CONNERS),
        q("CP100","Devient irritable lorsqu'anxieux/se.",O_CONNERS),
        q("CP101","Est facilement distrait/e par ce qu'il/elle voit ou entend.",O_CONNERS),
        q("CP102","S'obstine avec les adultes.",O_CONNERS),
        q("CP103","Est triste, morose ou irritable durant plusieurs journées consécutives.",O_CONNERS),
        q("CP104","Interrompt les autres, par exemple leurs conversations ou leurs jeux.",O_CONNERS),
        q("CP105","Est parfait/e en tout point.",O_CONNERS),
        q("CP106","Les problèmes de votre enfant affectent gravement ses travaux scolaires ou ses notes.",O_CONNERS),
        q("CP107","Les problèmes de votre enfant affectent gravement ses amitiés ou ses relations.",O_CONNERS),
        q("CP108","Les problèmes de votre enfant affectent gravement votre vie familiale.",O_CONNERS)
      ]}
  ],
  scoring:{
    type:'sum_items',
    certification:{source:'drive',status:'certifie'},
    items:['CP001','CP002','CP003','CP004','CP005','CP006','CP007','CP008','CP009','CP010','CP011','CP012','CP013','CP014','CP015','CP016','CP017','CP018','CP019','CP020','CP021','CP022','CP023','CP024','CP025','CP026','CP027','CP028','CP029','CP030','CP031','CP032','CP033','CP034','CP035','CP036','CP037','CP038','CP039','CP040','CP041','CP042','CP043','CP044','CP045','CP046','CP047','CP048','CP049','CP050','CP051','CP052','CP053','CP054','CP055','CP056','CP057','CP058','CP059','CP060','CP061','CP062','CP063','CP064','CP065','CP066','CP067','CP068','CP069','CP070','CP071','CP072','CP073','CP074','CP075','CP076','CP077','CP078','CP079','CP080','CP081','CP082','CP083','CP084','CP085','CP086','CP087','CP088','CP089','CP090','CP091','CP092','CP093','CP094','CP095','CP096','CP097','CP098','CP099','CP100','CP101','CP102','CP103','CP104','CP105','CP106','CP107','CP108'],
    maxTotal:324,
    note:"Source Drive Conners 3 Parent : 108 items cotés 0-3 en somme brute. Les deux questions ouvertes Q109/Q110 et les informations administratives ne sont pas codées ici car l'UI patient ne prend pas en charge les champs texte dans le catalogue. Aucune conversion T-score automatisée sans tables normatives validées."
  }
};
