// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { withSupabaseSslMode } from "./src/lib/postgres";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/runWithAlias.js prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ? withSupabaseSslMode(process.env["DATABASE_URL"]) : undefined,
  },
  // Tables SQL-brut hors schema.prisma : créées par des migrations versionnées
  // mais exclues du diff Prisma déclaratif. Deux raisons d'y être — un type
  // d'extension que Prisma ne modélise pas (`vector(1536)` : chunks, claims)
  // ou une mécanique portée par la base elle-même (journal des décisions :
  // triggers append-only et cohérence d'insertion).
  experimental: {
    externalTables: true,
  },
  tables: {
    external: [
      "public.rag_corpus_chunks",
      "public.rag_corpus_claims",
      "public.rag_corpus_claim_sources",
      "public.rag_corpus_claim_decisions",
    ],
  },
});
