// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { withSupabaseSslMode } from "./src/lib/postgres";

const migrationUrl = process.env["DIRECT_URL"] || process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/runWithAlias.js prisma/seed.ts",
  },
  datasource: {
    // Les migrations (notamment CREATE EXTENSION vector et HNSW) doivent
    // privilégier la connexion directe Supabase. Le runtime reste sur le pooler.
    url: migrationUrl ? withSupabaseSslMode(migrationUrl) : undefined,
  },
});
